/**
 * Inline the tested resolver and the PDF samples into the single-file mockup, so the
 * prototype and src/resolve.js can never drift apart.  node build.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const HTML = "mockup/marginalia.html";
const START = "/* <<< generated by build.mjs — edit src/resolve.js, not this >>> */";
const END = "/* <<< end generated >>> */";

const resolver = readFileSync("src/resolve.js", "utf8")
  .replace(/^export\s+/gm, "")
  .trim();

/*
 * pdf.js goes in as inert text and is turned into a blob module on first use, so a
 * dropped PDF is parsed for real in the browser with no network. It is optional: if the
 * package is not installed, or the host's CSP refuses blob: scripts, the page says so
 * and falls back to asking for the fields.
 */
const inert = (f) => readFileSync(f, "utf8").replace(/<\/script/gi, "<\\/script");
const PDFJS_DIR = "node_modules/pdfjs-dist/build/";
let pdfjsBlocks = "";
try {
  pdfjsBlocks =
    `<script id="pdfjs-lib" type="text/plain">${inert(PDFJS_DIR + "pdf.min.mjs")}</script>\n` +
    `<script id="pdfjs-worker" type="text/plain">${inert(PDFJS_DIR + "pdf.worker.min.mjs")}</script>\n`;
} catch {
  console.warn("pdfjs-dist not installed — the mockup will ship without PDF parsing");
}

/*
 * KaTeX, for the maths. Rendered to MathML rather than KaTeX's own HTML, which means no
 * stylesheet and none of its 60-odd font files — the browser draws it with the system
 * math font. ~270KB instead of ~900KB, and nothing to load from a CDN.
 */
try {
  pdfjsBlocks += `<script id="katex-lib" type="text/plain">${inert("node_modules/katex/dist/katex.min.js")}</script>\n`;
} catch {
  console.warn("katex not installed — the mockup will ship without maths rendering");
}

const block = `${START}\n${resolver}\n${END}`;

const PDFJS_START = "<!-- <<< pdf.js, inlined by build.mjs >>> -->";
const PDFJS_END = "<!-- <<< end pdf.js >>> -->";

const html = readFileSync(HTML, "utf8");
const a = html.indexOf(START), b = html.indexOf(END);
if (a === -1 || b === -1) throw new Error(`${HTML} is missing the generated-block markers`);
let out = html.slice(0, a) + block + html.slice(b + END.length);

const c = out.indexOf(PDFJS_START), d = out.indexOf(PDFJS_END);
if (c === -1 || d === -1) throw new Error(`${HTML} is missing the pdf.js markers`);
out = out.slice(0, c + PDFJS_START.length) + "\n" + pdfjsBlocks + out.slice(d);

writeFileSync(HTML, out);
console.log(`injected ${(block.length / 1024).toFixed(0)}KB resolver + ` +
            `${(pdfjsBlocks.length / 1024).toFixed(0)}KB pdf.js → ${(out.length / 1024).toFixed(0)}KB page`);
